### ISSUE TITLE
请问下如何使用AMQP自带的Tcp模块？

### ISSUE THREAD

**Issue by billchenchina** [MR-workaholic/RabbitMQCppDemo#1]
我看到您使用了自己写的`MyTool.h`和`MyHandler.h`，其中使用了`libev`，请问下`libev`是做什么用的呢？能不能够不使用libev来发送message？

自己比较菜鸡，，不太会用。。。谢谢！

**Comment by MR-workaholic** [comment]
你得先理解什么是IO复用函数，什么是事件循环等概念，要知道他们的作用。其实我现在的使用方法应该是最简单的了。我就是使用自带的TCP模块  +  一个开源事件循环库（无论如何都得要一个事件循环）。
    不使用libev也行的，libev是一个封装Linux一些IO复用函数如select，epoll等系统调用的库。如果不使用libev,libevent,boostasio等封装好select等系统调用的库的话，使用起来没那么方便。
    有读https://github.com/CopernicaMarketingSoftware/AMQP-CPP#tcp-connections这里一节吗？他的例程是MyTcpHandler 类继承了TcpHandler之后，必须实现monitor()，里面就是让AMQP客户端与select等系统调用-IO复用函数（事件循环）集合起来，当事件循环侦听到有数据发送给AMQP客户端后就开始调用AMQP客户端的函数来解析接收到的数据，注意到这句话吗：monitor()是为了the AMQP-CPP library to interact with the main event loop的。
    这个AMQP客户端库提供了与几款常用的开源事件循环库绑定在一起的类供我们使用，例如amqpcpp/libev.h里面的LibEvHandler类就是继承了TcpHandler之后，其monitor()将AMQP客户端库以及libev事件循环绑定在一起。当libev侦听到有数据发送给AMQP客户端的时候，就会自动调用AMQP的方法去解释数据。

**Comment by billchenchina** [comment]
@MR-workaholic 恩！十分感谢，我去学习一下事件循环！谢谢！
